services:
  api:
    image: api
    build:
      dockerfile: ./Dockerfile.api
    env_file:
      - .env
    ports:
      - 3000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3100:80
