services:
  api:
    image: api
    build:
      dockerfile: ./Dockerfile.api
    env_file:
      - .env
    ports:
      - 3000

  nginx:
    image: nginx
    build:
      dockerfile: Dockerfile.nginx
    ports:
      - 3100:80
